package org.example;

import javax.swing.*;
import java.awt.*;

public class GradientPanel extends JPanel {

    // all color code was completely generated by AI built off of AI built off of how we were trying to hand 2D graphics before, but this just looks so much better. Message commented below:


    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;

        // Define the dark blue gradient colors
        Color color1 = new Color(0, 0, 30);  // Near black-blue
        Color color2 = new Color(0, 20, 70); // Deep dark blue

        // Create a vertical gradient
        GradientPaint gp = new GradientPaint(0, 0, color1, 0, getHeight(), color2);

        g2d.setPaint(gp);
        g2d.fillRect(0, 0, getWidth(), getHeight());
    }
}




/*

To create a dark blue gradient background, you need to extend `JPanel` and override its `paintComponent` method to use `Graphics2D` with a `GradientPaint`.

### Step-by-step:
1.  **Create a custom panel class**: This class handles the actual drawing of the gradient.
2.  **Initialize the panel**: Replace the standard `JPanel` for `backgroundPanel` in your `frame` class with this new custom class.

`src/main/java/org/example/GradientPanel.java`
```java
package org.example;

import javax.swing.*;
import java.awt.*;

public class GradientPanel extends JPanel {
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;

        // Define the dark blue gradient colors
        Color color1 = new Color(0, 0, 30);  // Near black-blue
        Color color2 = new Color(0, 20, 70); // Deep dark blue

        // Create a vertical gradient
        GradientPaint gp = new GradientPaint(0, 0, color1, 0, getHeight(), color2);

        g2d.setPaint(gp);
        g2d.fillRect(0, 0, getWidth(), getHeight());
    }
}
```

In your `frame.java` constructor, replace the initialization of `backgroundPanel`:

```java
// Inside src/main/java/org/example/frame.java

// Replace: backgroundPanel = new JPanel();
backgroundPanel = new GradientPanel();
backgroundPanel.setLayout(null); // Ensure layout stays null for absolute positioning
```
 */